create table "public"."games" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "word" character varying(20) not null,
    "user_id" uuid not null default auth.uid(),
    "hint" character varying
);


alter table "public"."games" enable row level security;

CREATE UNIQUE INDEX games_id_key ON public.games USING btree (id);

CREATE UNIQUE INDEX games_pkey ON public.games USING btree (id);

alter table "public"."games" add constraint "games_pkey" PRIMARY KEY using index "games_pkey";

alter table "public"."games" add constraint "games_id_key" UNIQUE using index "games_id_key";

alter table "public"."games" add constraint "games_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."games" validate constraint "games_user_id_fkey";

create policy "Only see games you created"
on "public"."games"
as permissive
for all
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



